INSERT INTO leagues (league_id, league_name, country)
VALUES
    (1, 'Premier League', 'England'),
    (2, 'La Liga', 'Spain'),
    (3, 'Bundesliga', 'Germany'),
    (4, 'Serie A', 'Italy'),
    (5, 'Ligue 1', 'France'),
    (6, 'Eredivisie', 'Netherlands'),
    (7, 'Primeira Liga', 'Portugal'),
    (8, 'Brasileirão', 'Brazil'),
    (9, 'Argentine Primera División', 'Argentina'),
    (10, 'Scottish Premiership', 'Scotland'),
    (11, 'Süper Lig', 'Turkey'),
    (12, 'Belgian Pro League', 'Belgium'),
    (13, 'Russian Premier League', 'Russia'),
    (14, 'Ukrainian Premier League', 'Ukraine'),
    (15, 'Egyptian Premier League', 'Egypt'),
    (16, 'Saudi Pro League', 'Saudi Arabia'),
    (17, 'A-League', 'Australia'),
    (18, 'Canadian Premier League', 'Canada'),
    (19, 'Major League Soccer', 'USA'),
    (20, 'Liga MX', 'Mexico'),
    (21, 'Liga I', 'Romania'),
    (22, 'Super League Greece', 'Greece'),
    (23, 'Swiss Super League', 'Switzerland'),
    (24, 'Austrian Bundesliga', 'Austria'),
    (25, 'Danish Superliga', 'Denmark'),
    (26, 'Allsvenskan', 'Sweden'),
    (27, 'Eliteserien', 'Norway'),
    (28, 'Veikkausliiga', 'Finland'),
    (29, 'Ekstraklasa', 'Poland'),
    (30, 'NB I', 'Hungary'),
    (31, 'Serbian SuperLiga', 'Serbia'),
    (32, 'Croatian First Football League', 'Croatia'),
    (33, 'Slovak Super Liga', 'Slovakia'),
    (34, 'Bulgarian First League', 'Bulgaria'),
    (35, 'Moldovan National Division', 'Moldova'),
    (36, 'Cypriot First Division', 'Cyprus'),
    (37, 'Qatar Stars League', 'Qatar'),
    (38, 'J1 League', 'Japan'),
    (39, 'Chinese Super League', 'China'),
    (40, 'K League 1', 'South Korea'),
    (41, 'Indian Super League', 'India'),
    (42, 'Thai League 1', 'Thailand'),
    (43, 'Vietnamese V.League 1', 'Vietnam'),
    (44, 'Indonesian Liga 1', 'Indonesia'),
    (45, 'Iran Pro League', 'Iran'),
    (46, 'Israeli Premier League', 'Israel'),
    (47, 'South African Premier Division', 'South Africa'),
    (48, 'Zambian Super League', 'Zambia'),
    (49, 'Ghana Premier League', 'Ghana'),
    (50, 'Kenyan Premier League', 'Kenya'),
    (51, 'Tanzanian Premier League', 'Tanzania'),
    (52, 'Ugandan Premier League', 'Uganda'),
    (53, 'Zimbabwe Premier Soccer League', 'Zimbabwe'),
    (54, 'Botswana Premier League', 'Botswana'),
    (55, 'Malawian Super League', 'Malawi'),
    (56, 'Moroccan Botola Pro', 'Morocco'),
    (57, 'Tunisian Ligue Professionnelle 1', 'Tunisia'),
    (58, 'Algerian Ligue Professionnelle 1', 'Algeria'),
    (59, 'Senegal Premier League', 'Senegal'),
    (60, 'Ivory Coast Ligue 1', 'Ivory Coast'),
    (61, 'Ethiopian Premier League', 'Ethiopia'),
    (62, 'Sudanese Premier League', 'Sudan'),
    (63, 'Libyan Premier League', 'Libya'),
    (64, 'Angolan Girabola', 'Angola'),
    (65, 'Cameroon Elite One', 'Cameroon'),
    (66, 'DR Congo Linafoot', 'DR Congo'),
    (67, 'Gabon Championnat National D1', 'Gabon'),
    (68, 'Guinean Ligue 1', 'Guinea'),
    (69, 'Malian Première Division', 'Mali'),
    (70, 'Burkinabé Premier League', 'Burkina Faso'),
    (71, 'Niger Premier League', 'Niger'),
    (72, 'Chadian Premier League', 'Chad'),
    (73, 'Mauritanian Premier League', 'Mauritania'),
    (74, 'Cape Verde Premier League', 'Cape Verde'),
    (75, 'Namibian Premier League', 'Namibia'),
    (76, 'Eswatini Premier League', 'Eswatini'),
    (77, 'Mozambican Moçambola', 'Mozambique'),
    (78, 'Madagascar THB Champions League', 'Madagascar'),
    (79, 'Seychelles First Division', 'Seychelles'),
    (80, 'Mauritian Premier League', 'Mauritius'),
    (81, 'Comoros Premier League', 'Comoros'),
    (82, 'Rwandan Premier League', 'Rwanda'),
    (83, 'Burundi Premier League', 'Burundi'),
    (84, 'Somali Premier League', 'Somalia'),
    (85, 'Djibouti Premier League', 'Djibouti'),
    (86, 'Eritrean Premier League', 'Eritrea'),
    (87, 'Saudi First Division', 'Saudi Arabia'),
    (88, 'Qatari Second Division', 'Qatar'),
    (89, 'Emirati Pro League', 'UAE'),
    (90, 'Omani Professional League', 'Oman'),
    (91, 'Kuwaiti Premier League', 'Kuwait'),
    (92, 'Bahraini Premier League', 'Bahrain'),
    (93, 'Yemeni League', 'Yemen'),
    (94, 'Iraqi Premier League', 'Iraq'),
    (95, 'Afghan Premier League', 'Afghanistan'),
    (96, 'Pakistani Premier League', 'Pakistan'),
    (97, 'Bangladesh Premier League', 'Bangladesh'),
    (98, 'Nepal Super League', 'Nepal'),
    (99, 'Bhutan Premier League', 'Bhutan'),
    (100, 'Maldivian Dhivehi Premier League', 'Maldives');